#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.native.ignoreDisabledTargets=true
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
kotlin.incremental.native=true